# colang_version: "1.0"

# models:
#   - type: main
#     engine: openai
#     model: llama-3.3-70b-versatile
#     parameters:
#       base_url: "https://api.groq.com/openai/v1"
#       openai_api_key: "${GROQ_API_KEY}"
#       temperature: 0.1

# rails:
#   input:
#     flows:
#       - self check input
#   output:
#     flows:
#       - self check hallucination
#       - verify market topic alignment

# config:
#   self_check_input:
#     check_against_context: false
#   self_check_hallucination:
#     check_against_context: true
colang_version: "1.0"

models:
  - type: main
    engine: ollama
    model: llama3

rails:
  input:
    flows:
      - self check input
  output:
    flows:
      - self check hallucination
      - verify market topic alignment